### ISSUE TITLE
docs/Install.md out of date

### ISSUE THREAD

**Issue by speaker** [mikewongtkd/freescoretkd#2]
The INSTALL.md file appears out of date.

- Frontend systems:
  - ~/freescoretkd/frontend/html -> /var/www/html/freescore
  - ~/freescoretkd/frontend/cgi-bin -> /var/www/cgi-bin/freescore
- Backend systems:
  - ~/freescoretkd/backend -> /usr/local/freescore

frontend and backend are both under trunk, not directly under freescoretkd

**Comment by mikewongtkd** [comment]
Noted and updated, thanks!

- mike
