### ISSUE TITLE
No meaningful error is reported when there is no competition defined

### ISSUE THREAD

**Issue by speaker** [mikewongtkd/freescoretkd#3]
If there is not /Volume/ramdisk/test directory defined, an error state response should be generated. Presently, an Access-Control... error is likely becuase no headers are generated at all, resulting in a 500 from Apache.

**Comment by mikewongtkd** [comment]
Hi Adam,

The whole database setup needs work; I should have time to resume working on this presently. Stay tuned!

- mike
