### ISSUE TITLE
Help setting up server

### ISSUE THREAD

**Issue by DragonSlayer1514** [mikewongtkd/freescoretkd#6]
.

**Comment by mikewongtkd** [comment]
The backend may no longer support the default frontend, as I've been
building a newer frontend that will be merged back at some point.

I recommend version 4.2 as last known good. I don't support setup
instructions beyond what I've already written.

Best regards,

- Mike

**Comment by DragonSlayer1514** [comment]
Hi, so i don't know if I did something wrong, but the resgistration.php pages are not showing anything. I have tried opening it by itself but it still doesn't show anything.

**Comment by DragonSlayer1514** [comment]
I am pretty sure in apache2, php, cgi, and perl are enabled and seem to be working.

**Comment by DragonSlayer1514** [comment]
@mikewongtkd 
![image](https://user-images.githubusercontent.com/33702928/115468043-161ea300-a1f8-11eb-8c0d-3732c06871e4.png)
This is the jquery error that might be the problem?

**Comment by DragonSlayer1514** [comment]
@mikewongtkd Hi, how do i access the scoring page?

**Comment by DragonSlayer1514** [comment]
Also, everytime i click a section, i get 4 errors saying Grassroots, Freescore setup, Freescore worldclass, and Freescore freestyle systems failed to start.
